apiVersion: v1
kind: Service
metadata:
  name: greeting-server-service
spec:
  selector:
    app: greeting-server
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: LoadBalancer